
import { Inter } from "next/font/google";
import "./globals.css";
import { redirect } from "next/navigation";
import Navlinks from "@/components/Navlinks";
import { AuthProvider } from "./Providers";

const inter = Inter( { subsets: [ "latin" ] } );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( { children } )
{

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex flex-col">
            <div className="h-20 bg-red-300 flex items-center justify-between p-1 md:px-16">
              <div className="text-4xl">
                Logo
              </div>
              <Navlinks />
            </div>
            <div className="flex-grow">
              {children}
            </div>
            <div className="h-20 ">
              navbar
            </div>
          </div>
        </AuthProvider>
      </body>
    </html >
  );
}
